### ISSUE TITLE
Docker container doesn't auto start

### ISSUE THREAD

**Issue by jerheij** [panubo/docker-sshd#14]
OS: CentOS 7
Docker: docker-ce-18.06.1.ce-3.el7.x86_64

I am having issues with running this docker container, it works once it has been pulled and started. But when I reset the server I need to manually bring the server down with docker-compose and then up it again, otherwise it just keeps restarting.

I tested this on a virtual Debian docker server and a physical CentOS server.

Docker-compose.yml:

```
---
version: '3.1'
services:
  bastion:
    image: panubo/sshd:latest
    container_name: bastion
    restart: always
    ports:
      - "x.x.x.x:xyz:22"
    volumes:
      - /opt/sshd/config/authorized_keys:/home/user/.ssh/authorized_keys
      - /opt/sshd/config/known_hosts:/home/user/.ssh/known_hosts
      - /opt/sshd/config/ssh-key:/home/user/.ssh/id_rsa:ro
      - /opt/sshd/config/ssh-key.pub:/home/user/.ssh/id_rsa.pub:ro
      - /opt/sshd/config/ssh_config:/home/user/.ssh/config:ro
      - /opt/sshd/config/.profile:/home/user/.profile:ro
      - /opt/sshd/config/keys:/etc/ssh/keys:ro
      - /opt/docker_config/resolv.conf:/etc/resolv.conf:ro
    environment:
      - SSH_USERS=user:505:505
```
