### ISSUE TITLE
Unable to login to SSH in github actions

### ISSUE THREAD

**Issue by tbhaxor** [panubo/docker-sshd#71]
I am using github actions and your docker image to test my tool.

Here is my config

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
   branches:
    - main
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ubuntu-latest
          
    services:
      ssh: panubo/sshd 
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get container information
        id: conf
        run: |
          echo "::set-output name=DOCKER_ID::$(docker ps -q)"
          echo "::set-output name=DOCKER_IP::$(docker exec $(docker ps -q) ifconfig eth0 | cut -d ':' -f 2 | sed -n '2p' | cut -d ' ' -f 1)"
      
      - name: Create SSH Keys
        run: |
          sudo rm -rf /keys
          sudo mkdir /keys 
          sudo chown $USER:$USER /keys -R
          ssh-keygen -f /keys/src -N ''
          ssh-keygen -f /keys/dest -N ''
      
      - name: Setup source user
        run: |
          docker exec ${{ steps.conf.outputs.DOCKER_ID }} mkdir -p /home/src/.ssh
          docker exec ${{ steps.conf.outputs.DOCKER_ID }} useradd -d /home/src src
          docker cp /keys/src.pub ${{ steps.conf.outputs.DOCKER_ID }}:/home/src/.ssh/authorized_keys
          docker exec ${{ steps.conf.outputs.DOCKER_ID }} chown src:src -Rv /home/src
          
      - name: Setup destination user
        run: |
          docker exec ${{ steps.conf.outputs.DOCKER_ID }} mkdir -p /home/dest/.ssh
          docker exec ${{ steps.conf.outputs.DOCKER_ID }} useradd -d /home/dest dest
          docker cp /keys/dest.pub ${{ steps.conf.outputs.DOCKER_ID }}:/home/dest/.ssh/authorized_keys
          docker exec ${{ steps.conf.outputs.DOCKER_ID }} chown dest:dest -Rv /home/dest
        
      - name: Check ssh connection
        run: ssh -i /keys/src src@${{ steps.conf.outputs.DOCKER_IP }} "whoami"
```

I am getting this error

![image](https://user-images.githubusercontent.com/28386721/118431210-6acc1580-b6f3-11eb-8ffb-89938561495e.png)
