### ISSUE TITLE
SFTP_MODE issue

### ISSUE THREAD

**Issue by vaaraniemi** [panubo/docker-sshd#79]
With SFTP_MODE set to false (default) connections work fine. When set true it takes around 5 minutes to connect after the connection has been accepted. Also docker stats shows abnormally high cpu usage when trying to connect. The docker logs show no warnings or error messages when connecting.

Here is my docker-compose:
```
sftp:
    image: panubo/sshd
    restart: always
    env_file:
      - sftp.env
    volumes:
      - sftp-web-data:/public
      - ./setpasswd.sh:/etc/entrypoint.d/setpasswd.sh
      - ./id_rsa.pub:/etc/authorized_keys/user1:ro
    ports:
      - "2222:22"
```

And sftp.env:
```
SFTP_MODE=true
SFTP_CHROOT="/public"

#change password in setpassword.sh
SSH_USERS=user1:1000:1000
SSH_ENABLE_PASSWORD_AUTH=true
```

Any help would be appreciated!
